// <auto-generated />
using System;
using HomeApp.Infrastructure.Persistance;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HomeApp.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616221528_AddSortOrderAndCreatedAtToMaterial")]
    partial class AddSortOrderAndCreatedAtToMaterial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HomeApp.Domain.Entities.Contact", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.FamilyMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Age")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("FamilyMembers");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HomeProject", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal?>("Budget")
                        .HasColumnType("numeric");

                    b.Property<DateOnly?>("CompletedDate")
                        .HasColumnType("date");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("StartDate")
                        .HasColumnType("date");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HomeProjects");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HomeProjectContact", b =>
                {
                    b.Property<Guid>("HomeProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ContactId")
                        .HasColumnType("uuid");

                    b.Property<string>("Role")
                        .HasColumnType("text");

                    b.HasKey("HomeProjectId", "ContactId");

                    b.HasIndex("ContactId");

                    b.ToTable("HomeProjectContacts");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HomeProjectMaterial", b =>
                {
                    b.Property<Guid>("HomeProjectId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("MaterialId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("QuantityNeeded")
                        .HasColumnType("numeric");

                    b.HasKey("HomeProjectId", "MaterialId");

                    b.HasIndex("MaterialId");

                    b.ToTable("HomeProjectMaterials");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HouseholdTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssignedMemberId")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<DateOnly?>("DueDate")
                        .HasColumnType("date");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<int>("Recurrence")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssignedMemberId");

                    b.ToTable("HouseholdTasks");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.Material", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Icon")
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<decimal?>("Quantity")
                        .HasColumnType("numeric");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<string>("Unit")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Materials");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.Photo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeProjectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("HomeProjectId");

                    b.ToTable("Photos");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.ProgressEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateOnly>("Date")
                        .HasColumnType("date");

                    b.Property<Guid>("HomeProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeProjectId");

                    b.ToTable("ProgressEntries");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.ProjectLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("HomeProjectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("HomeProjectId");

                    b.ToTable("ProjectLinks");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HomeProjectContact", b =>
                {
                    b.HasOne("HomeApp.Domain.Entities.Contact", "Contact")
                        .WithMany("HomeProjects")
                        .HasForeignKey("ContactId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeApp.Domain.Entities.HomeProject", "HomeProject")
                        .WithMany("Contacts")
                        .HasForeignKey("HomeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Contact");

                    b.Navigation("HomeProject");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HomeProjectMaterial", b =>
                {
                    b.HasOne("HomeApp.Domain.Entities.HomeProject", "HomeProject")
                        .WithMany("Materials")
                        .HasForeignKey("HomeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeApp.Domain.Entities.Material", "Material")
                        .WithMany("HomeProjects")
                        .HasForeignKey("MaterialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeProject");

                    b.Navigation("Material");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HouseholdTask", b =>
                {
                    b.HasOne("HomeApp.Domain.Entities.FamilyMember", "AssignedMember")
                        .WithMany()
                        .HasForeignKey("AssignedMemberId");

                    b.Navigation("AssignedMember");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.Photo", b =>
                {
                    b.HasOne("HomeApp.Domain.Entities.HomeProject", "HomeProject")
                        .WithMany("Photos")
                        .HasForeignKey("HomeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeProject");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.ProgressEntry", b =>
                {
                    b.HasOne("HomeApp.Domain.Entities.HomeProject", "HomeProject")
                        .WithMany("ProgressEntries")
                        .HasForeignKey("HomeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeProject");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.ProjectLink", b =>
                {
                    b.HasOne("HomeApp.Domain.Entities.HomeProject", "HomeProject")
                        .WithMany("Links")
                        .HasForeignKey("HomeProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeProject");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.Contact", b =>
                {
                    b.Navigation("HomeProjects");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.HomeProject", b =>
                {
                    b.Navigation("Contacts");

                    b.Navigation("Links");

                    b.Navigation("Materials");

                    b.Navigation("Photos");

                    b.Navigation("ProgressEntries");
                });

            modelBuilder.Entity("HomeApp.Domain.Entities.Material", b =>
                {
                    b.Navigation("HomeProjects");
                });
#pragma warning restore 612, 618
        }
    }
}
